### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by shotanue** [ray-di/Ray.MediaQuery#14]
現在Ray.Queryをプロジェクトで使用していますが、Ray.MediaQueryの利用、変更を検討しています。

しかしながらRay.MediaQueryのminバージョンが7.4以上になっており、この点が導入のボトルネックになっています。
minバージョン指定が7.3になるとプロジェクトに導入しやすいため、検討いただけると嬉しいです。

https://github.com/ray-di/Ray.MediaQuery/blob/141570ac99b81caa9f31fe687768b0d84a628493/composer.json#L12

**Comment by koriym** [comment]
対応してリリースしました！ https://github.com/ray-di/Ray.MediaQuery/releases/tag/0.3.0

**Comment by shotanue** [comment]
ありがとうございます!!!!
