### ISSUE TITLE
getRowから呼ばれるクエリ結果が空の場合にundefined offsetが発生する

### ISSUE THREAD

**Issue by shotanue** [ray-di/Ray.MediaQuery#16]
sqlファイル名のポストフィックスが`item`など、SqlQuery::getRowが呼ばれるケースで、結果セットが空の時にundefined offsetが発生してしまいます。

https://github.com/ray-di/Ray.MediaQuery/blob/4fcc7d146eea03359947c16f8c34381dcaac17c3/src/SqlQuery.php#L84-L87

結果が取得できなかった際の戻り値としては、空配列またはnullを期待していたのですが、意図した動作でしょうか？

**Comment by koriym** [comment]
Bugだと思います！$rowListがnullだったら空配列返せば良さそうですね。
PRしてもらっていいでしょうか？

**Comment by koriym** [comment]
リリースしました！
https://github.com/ray-di/Ray.MediaQuery/releases/tag/0.3.1
