### ISSUE TITLE
Getting a nested array when multiple rows are linked to a single entry

### ISSUE THREAD

**Issue by mstysk** [ray-di/Ray.MediaQuery#47]
# Why

I want to use an Entity with a 1-to-many data structure relationship, but it seems that it is currently not possible.

# Suggestion

By using [php.net:PDO::FETCH_NAMED](https://www.php.net/manual/en/pdostatement.fetch.php), it seems that if there are multiple values, they will be stored in an array.

This might also be helpful: [phpdelusions.net::FETCH_NAMED](https://phpdelusions.net/pdo/fetch_modes)

**Comment by koriym** [comment]
Good idea! Could you create a test for that?

**Comment by mstysk** [comment]
Got it. I try to write a test.
